### ISSUE TITLE
WOTLK Classic Support

### ISSUE THREAD

**Issue by maximus210793** [ketho-wow/LargerMacroIconSelection#1]
Hi,
Can you update for WOTLK Classic please? 
Would be awesome, thanks a lot!

**Comment by Ketho** [comment]
I want to update it but I did have some issues with wotlk classic, since wow.tools no longer provides the wotlk icon data. I will try to find a solution this week

**Comment by maximus210793** [comment]
Thanks for having a look <3

**Comment by Ketho** [comment]
Just a quick update, it's still on my todo list...

**Comment by Ketho** [comment]
The v1.8.0-beta release should also support wrath classic 3.4.0 but I couldn't test it since the classic PTR is down 😞

**Comment by Ketho** [comment]
Now the Classic PTR is on 3.4.1 so I still can't test it on the current classic servers 😅 

Can you maybe check if [v1.8.0](https://github.com/ketho-wow/LargerMacroIconSelection/releases/tag/v1.8.0) works?
