### ISSUE TITLE
Doesnt work after TWW update

### ISSUE THREAD

**Issue by faradriel** [ketho-wow/LargerMacroIconSelection#10]
now when I open it doesnt serach and doesnt let me scroll down and then It only shows the ? 

is this going to be updated?

**Comment by Ketho** [comment]
yeah, but I think I need some time to take a look at it

**Comment by faradriel** [comment]
> yeah, but I think I need some time to take a look at it

sounds good, thank you!

**Comment by Ketho** [comment]
Should be fixed in 1.9.5 :)
https://github.com/ketho-wow/LargerMacroIconSelection/releases/tag/v1.9.5

**Comment by faradriel** [comment]
> Should be fixed in 1.9.5 :) https://github.com/ketho-wow/LargerMacroIconSelection/releases/tag/v1.9.5

thank you!!!! it is working!
