### ISSUE TITLE
10.1 Error: Invalid addon name...

### ISSUE THREAD

**Issue by nancikennedy** [ketho-wow/LargerMacroIconSelection#5]
Using v1.8.1, on Retail, I am getting an error when trying to use the search function.

8x ...lector-1.0-LMIS/LibAdvancedIconSelector-1.0-LMIS.lua:228: bad argument #1 to 'GetAddOnMetadata' (Invalid AddOn name AdvancedIconSelector-KeywordData. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable))
[string "=[C]"]: in function `GetAddOnMetadata'
[string "@LargerMacroIconSelection/Libs/LibAdvancedIconSelector-1.0-LMIS/LibAdvancedIconSelector-1.0-LMIS.lua"]:228: in function `LoadKeywords'
[string "@LargerMacroIconSelection/Libs/LibAdvancedIconSelector-1.0-LMIS/LibAdvancedIconSelector-1.0-LMIS.lua"]:1130: in function `RestartSearch'
[string "@LargerMacroIconSelection/Libs/LibAdvancedIconSelector-1.0-LMIS/LibAdvancedIconSelector-1.0-LMIS.lua"]:1120: in function `func'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = "AdvancedIconSelector-KeywordData"
(*temporary) = "X-Revision"
(*temporary) = "Invalid AddOn name AdvancedIconSelector-KeywordData. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable)"

**Comment by SpareSimian** [comment]
Look for the lines in LargerMacroIconSelection/Libs/LibAdvancedIconSelector-1.0-LMIS/LibAdvancedIconSelector-1.0-LMIS.lua that call "GetAddOnInfo(5" and change the 5 to a 4. The enabled flag in the return values in that API was removed so the loadable flag is now the 4th, not the 5th. See here:

https://wowpedia.fandom.com/wiki/API_GetAddOnInfo

**Comment by Ketho** [comment]
> Look for the lines in LargerMacroIconSelection/Libs/LibAdvancedIconSelector-1.0-LMIS/LibAdvancedIconSelector-1.0-LMIS.lua that call "GetAddOnInfo(5" and change the 5 to a 4. The enabled flag in the return values in that API was removed so the loadable flag is now the 4th, not the 5th.

Thanks for the CurseForge comment 🙂 I apparently didn't get notifications for this repo
