### ISSUE TITLE
Ajour downloader can't find new releases

### ISSUE THREAD

**Issue by SpareSimian** [ketho-wow/LargerMacroIconSelection#6]
Some kind of packaging issue. Ajour (an alternative addon updater that can download from GitHub) sees the v1.8.0-beta tag but not the v1.8.3 release. I think it wants a git tag to recognize the newer release. I see the beta was generated by github-actions so maybe that's needed to generate the tag. I'd also read that there's a script from the BigWigs authors for automating that. 

https://wowpedia.fandom.com/wiki/Using_the_BigWigs_Packager_with_GitHub_Actions

**Comment by Ketho** [comment]
Huh, but the v1.8.3 release is also generated by github-actions so I'm not sure why Ajour would pick the v1.8.0-beta instead. I've gone ahead and deleted it. I'm indeed using the bigwigs packager.

**Comment by SpareSimian** [comment]
That seems to have fixed it. Ajour found v1.8.3 as an update. So maybe the "-beta" was confusing it.
