### ISSUE TITLE
LibAdvancedIconSelector-1.0-LMIS.lua:228: bad argument #1 to 'GetAddOnMetadata' (Invalid AddOn name AdvancedIconSelector-KeywordData.

### ISSUE THREAD

**Issue by Ookami313** [ketho-wow/LargerMacroIconSelection#7]
Tried using the search bar looking for an icon while creating a new gear set on an alt and I ran into the following error. Search doesn't work, and will produce the error each time I try to type in a letter. Thanks.

11x ...lector-1.0-LMIS/LibAdvancedIconSelector-1.0-LMIS.lua:228: bad argument #1 to 'GetAddOnMetadata' (Invalid AddOn name AdvancedIconSelector-KeywordData. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable))
[string "=[C]"]: in function `GetAddOnMetadata'
[string "@LargerMacroIconSelection/Libs/LibAdvancedIconSelector-1.0-LMIS/LibAdvancedIconSelector-1.0-LMIS.lua"]:228: in function `LoadKeywords'
[string "@LargerMacroIconSelection/Libs/LibAdvancedIconSelector-1.0-LMIS/LibAdvancedIconSelector-1.0-LMIS.lua"]:1130: in function `RestartSearch'
[string "@LargerMacroIconSelection/Libs/LibAdvancedIconSelector-1.0-LMIS/LibAdvancedIconSelector-1.0-LMIS.lua"]:1120: in function `func'
[string "@DataStore/libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = "AdvancedIconSelector-KeywordData"
(*temporary) = "X-Revision"
(*temporary) = "Invalid AddOn name AdvancedIconSelector-KeywordData. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable)"

**Comment by Ketho** [comment]
Sorry for the late reply, can you try if it works in v1.8.4

**Comment by Ookami313** [comment]
Ticket was closed by the time I saw this, but jut updated and tested and everything looks to be working fine now. Thanks for the update.
